export interface User
{
    id: number;
    username: string;
    avatar: string;
    memberSince: string;
    friendIds: Array<number>;
    posts: Array<Posts>;
}

export interface Posts
{
    id: number;
    title: string;
    subtitle: string;
    content: string;
}

export interface UserDetails extends User
{
    mutualFriends: Array<User>;
}


export const usersMock: Array<User> = [
    {
        id: 1,
        username: "João Figueiredo",
        avatar: "/assets/avatars/avatar1.jpg",
        memberSince: "2014-05-03T16:12Z",
        friendIds: [2, 4],
        posts: [{
            id: 1,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
            Caros amigos, a mobilidade dos capitais internacionais desafia a capacidade de equalização das diversas correntes de pensamento. Nunca é demais lembrar o peso e o significado destes problemas, uma vez que a necessidade de renovação processual ainda não demonstrou convincentemente que vai participar na mudança das diretrizes de desenvolvimento para o futuro. O cuidado em identificar pontos críticos na complexidade dos estudos efetuados é uma das consequências das direções preferenciais no sentido do progresso. Do mesmo modo, a adoção de políticas descentralizadoras não pode mais se dissociar dos modos de operação convencionais
            </p>`
        },
        {
            id: 2,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 3,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        }]
    },
    {
        id: 2,
        username: "Joana Vasconcellos",
        avatar: "/assets/avatars/avatar2.jpg",
        memberSince: "2015-05-02T11:32Z",
        friendIds: [1, 4],
        posts: [{
            id: 4,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 5,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 6,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 7,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 8,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 9,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 10,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 11,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 12,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        }]
    },
    {
        id: 3,
        username: "Arthur Silveira",
        avatar: "/assets/avatars/avatar3.jpg",
        memberSince: "2016-02-01T18:19Z",
        friendIds: [],
        posts: [{
            id: 13,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        }]
    },
    {
        id: 4,
        username: "Clara Passos",
        avatar: "/assets/avatars/avatar4.jpg",
        memberSince: "2014-05-09T22:12Z",
        friendIds: [1, 2, 5, 6],
        posts: [{
            id: 14,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis Arthur Silveiraeleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 15,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        }]
    },
    {
        id: 5,
        username: "Mauro Andrade",
        avatar: "/assets/avatars/avatar5.jpg",
        memberSince: "2013-09-01T20:22Z",
        friendIds: [4, 6],
        posts: [{
            id: 16,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis Arthur Silveiraeleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 17,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        }]
    },
    {
        id: 6,
        username: "Rafaela Moreira",
        avatar: "/assets/avatars/avatar6.jpg",
        memberSince: "2014-02-03T15:33Z",
        friendIds: [4, 5],
        posts: [{
            id: 18,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis Arthur Silveiraeleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        },
        {
            id: 19,
            title: "Título de um post criado por um usuário deste blog",
            subtitle: "Usuários que utilizam este blog podem ter, ou não, interesse em criar posts",
            content: `<p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed felis dolor, fringilla eu eleifend non, hendrerit hendrerit orci. Proin vitae tincidunt metus, eget finibus elit. Maecenas dolor enim, commodo vitae suscipit eu, laoreet et eros. Quisque ornare sodales ante dignissim pharetra. Suspendisse in nisi dui. Donec ut luctus magna, quis porta ipsum. Mauris hendrerit sit amet nibh vel venenatis. Quisque accumsan tortor id consectetur blandit. Ut eget maximus velit, ac imperdiet orci. Mauris auctor, eros ac gravida tincidunt, risus velit porta arcu, ac sollicitudin dui est nec leo. Vivamus tristique egestas venenatis. Sed venenatis eleifend risus vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac tellus pharetra, efficitur tortor et, pharetra ex. Nam pulvinar odio ut nisl viverra tincidunt. Ut scelerisque augue ex, at gravida sem ultrices et. Vivamus sit amet mi nibh. Nullam lacinia velit laoreet libero lobortis tincidunt ut a ex. Nunc auctor hendrerit risus. Donec risus mauris, interdum non ligula ac, tristique ornare justo. Curabitur vel tortor ac libero interdum finibus eu vel urna. Fusce tempor, lacus id efficitur convallis, neque massa pharetra sem, id maximus ligula libero at libero. Cras ipsum quam, lobortis in elit at, tincidunt pellentesque mauris. Aliquam dapibus orci ut blandit tempor. Morbi consectetur dapibus massa id cursus. Quisque vel mollis sapien. Suspendisse scelerisque pellentesque ipsum at ultrices. Fusce in ligula accumsan, maximus eros ut, porttitor nunc. Ut in mi neque. Sed sollicitudin consequat turpis, non congue arcu finibus vitae. Phasellus in vestibulum risus. Donec lacus est, scelerisque vulputate tellus at, suscipit porta dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt ultrices est, nec accumsan quam bibendum sed. Praesent ac condimentum magna. Fusce vel maximus nisi. Quisque nec arcu blandit, rhoncus risus vitae, convallis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent vel ultricies purus. Aliquam vulputate ullamcorper dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec lobortis dictum enim quis porttitor. Suspendisse augue augue, facilisis vitae bibendum nec, viverra nec metus. In vel nisl nec ipsum vestibulum interdum vel eget lorem. Duis suscipit, ante at sagittis blandit, massa nunc elementum urna, et accumsan arcu massa non dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </p>`
        }]
    }
]
